/**
 * Occupational exposure modeling - Comprehensive Chemical Database
 * Compiled from ACGIH 2025 TLVs and BEIs & NIOSH Pocket Guide to Chemical Hazards (NPG).
 * 100% Offline Capable for Web and Android APK.
 */

export const COMPREHENSIVE_CHEMICAL_DATABASE = [
  {
    name: "Acetaldehyde",
    synonyms: "Acetic aldehyde, Ethanal, Ethyl aldehyde",
    cas: "75-07-0",
    rtecs: "AB1925000",
    dot: "1089 129",
    formula: "CH3CHO",
    mw: 44.05,
    bp: "69°F (20.6°C)",
    vp20: 740,
    density: 0.79,
    flp: "-36°F (-38°C)",
    lel: 4.0,
    uel: 60.0,
    acgihTlvTwa: null,
    acgihTlvStel: null,
    acgihTlvC: 25,
    acgihNotations: "A2 (Suspected Human Carcinogen)",
    acgihTlvBasis: "Eye & URT irr",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 200,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "Ca [2000 ppm]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, nose, throat; erythema; burns; conjunctivitis; cough; CNS depression; delayed pulmonary edema; in animals: kidney, reproductive & teratogenic effects; nasal cancer",
    targetOrgans: "Eyes, skin, respiratory system, kidneys, CNS, reproductive system",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acetic acid",
    synonyms: "Ethanoic acid, Glacial acetic acid, Vinegar acid",
    cas: "64-19-7",
    rtecs: "AF1225000",
    dot: "2789 132 (>80%); 2790 153 (10-80%)",
    formula: "CH3COOH",
    mw: 60.05,
    bp: "244°F (118°C)",
    vp20: 11.4,
    density: 1.05,
    flp: "103°F (39°C)",
    lel: 4.0,
    uel: 19.9,
    acgihTlvTwa: 10,
    acgihTlvStel: 15,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "URT & eye irr; pulmonary function",
    acgihBei: null,
    nioshRelTwa: 10,
    nioshRelStel: 15,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 10,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "50 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, nose, throat; eye/skin burns; skin sensitization; dental erosion; black skin, hyperkeratosis; conjunctivitis; lacrimation; pharyngeal edema; chronic bronchitis",
    targetOrgans: "Eyes, skin, respiratory system, teeth",
    respirator: "50 ppm: Sa:Cf/Paprov/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acetic anhydride",
    synonyms: "Acetyl oxide, Acetic oxide, Ethanoic anhydride",
    cas: "108-24-7",
    rtecs: "AK1925000",
    dot: "1715 137",
    formula: "(CH3CO)2O",
    mw: 102.09,
    bp: "282°F (139°C)",
    vp20: 4.0,
    density: 1.08,
    flp: "120°F (49°C)",
    lel: 2.7,
    uel: 10.3,
    acgihTlvTwa: 1,
    acgihTlvStel: 3,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "Eye & URT irr",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: 5,
    nioshCa: false,
    oshaPelTwa: 5,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "200 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Conjunctivitis, lacrimation, corneal edema, photophobia; nasal & pharyngeal irritation; cough, dyspnea, bronchitis; skin burns; skin sensitization",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "125 ppm: Sa:Cf/PaprOv; 200 ppm: CcrFOv/GmFOv/PaprTOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acetone",
    synonyms: "Dimethyl ketone, 2-Propanone, Pyroacetic ether",
    cas: "67-64-1",
    rtecs: "AL3150000",
    dot: "1090 127",
    formula: "(CH3)2CO",
    mw: 58.08,
    bp: "133°F (56.2°C)",
    vp20: 185.5,
    density: 0.791,
    flp: "0°F (-18°C)",
    lel: 2.5,
    uel: 12.8,
    acgihTlvTwa: 250,
    acgihTlvStel: 500,
    acgihTlvC: null,
    acgihNotations: "A4 (Not Classifiable as Human Carcinogen); BEI",
    acgihTlvBasis: "URT & eye irr; CNS impair",
    acgihBei: "Acetone in urine: 25 mg/L, End of shift",
    nioshRelTwa: 250,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 1000,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "2500 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, nose, throat; headache, dizziness, lightheadedness; CNS depression; dermatitis",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "2500 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acetonitrile",
    synonyms: "Cyanomethane, Methyl cyanide, Ethanenitrile",
    cas: "75-05-8",
    rtecs: "AL7700000",
    dot: "1648 127",
    formula: "CH3CN",
    mw: 41.05,
    bp: "179°F (81.6°C)",
    vp20: 72.8,
    density: 0.786,
    flp: "42°F (5.6°C)",
    lel: 3.0,
    uel: 16.0,
    acgihTlvTwa: 20,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A4",
    acgihTlvBasis: "LRT irr",
    acgihBei: null,
    nioshRelTwa: 20,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 40,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "500 ppm",
    routes: "Inhalation, Ingestion, Skin absorption, Contact",
    symptoms: "Irritation of throat; asphyxia; nausea, vomiting; chest pain; lassitude, stupor, convulsions; in animals: liver & kidney damage",
    targetOrgans: "Respiratory system, cardiovascular system, CNS, liver, kidneys",
    respirator: "200 ppm: CcrOv/Sa; 500 ppm: Sa:Cf/PaprOv/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acetylene",
    synonyms: "Ethine, Ethyne, Narcylene",
    cas: "74-86-2",
    rtecs: "AO9600000",
    dot: "1001 116",
    formula: "HC≡CH",
    mw: 26.04,
    bp: "-119°F (-84°C, sublimes)",
    vp20: 33500, // gas at ambient
    density: 0.91, // gas relative to air
    flp: "NA (Gas)",
    lel: 2.5,
    uel: 100.0,
    acgihTlvTwa: null,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Minimal Oxygen Content (D, EX)",
    acgihTlvBasis: "Asphyxia",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: 2500,
    nioshCa: false,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "N.D. (Flammable gas)",
    routes: "Inhalation, Skin/Eye contact (liquid)",
    symptoms: "Headache, dizziness; asphyxia; liquid: frostbite",
    targetOrgans: "CNS, respiratory system",
    respirator: "Acetylene Criteria Document recommendations",
    firstAid: "Eye: Frostbite wash; Skin: Frostbite treatment; Breath: Fresh air"
  },
  {
    name: "Acrolein",
    synonyms: "Acrylaldehyde, 2-Propenal, Acrylic aldehyde",
    cas: "107-02-8",
    rtecs: "AS1050000",
    dot: "1092 131P",
    formula: "CH2=CHCHO",
    mw: 56.06,
    bp: "127°F (52.8°C)",
    vp20: 210,
    density: 0.84,
    flp: "-15°F (-26°C)",
    lel: 2.8,
    uel: 31.0,
    acgihTlvTwa: null,
    acgihTlvStel: null,
    acgihTlvC: 0.05,
    acgihNotations: "Skin; RSEN; OTO; A4",
    acgihTlvBasis: "Eye irr",
    acgihBei: null,
    nioshRelTwa: 0.1,
    nioshRelStel: 0.3,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 0.1,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "2 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, mucous membranes; decreased pulmonary function; delayed pulmonary edema; chronic respiratory disease",
    targetOrgans: "Eyes, skin, respiratory system, heart",
    respirator: "2 ppm: Sa:Cf/PaprOv/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acrylamide",
    synonyms: "Acrylamide monomer, 2-Propenamide, Acrylic amide",
    cas: "79-06-1",
    rtecs: "AS3325000",
    dot: "2074 153P",
    formula: "CH2=CHCONH2",
    mw: 71.08,
    bp: "Decomposes at 347°F",
    vp20: 0.007,
    density: 1.12,
    flp: "280°F (138°C)",
    lel: null,
    uel: null,
    acgihTlvTwa: 0.03, // mg/m3 (IFV)
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; DSEN; A2 (Suspected Human Carcinogen); BEI",
    acgihTlvBasis: "CNS & PNS impair; cancer",
    acgihBei: "N-(2-Carbamoylethyl)valine in blood: 500 pmol/g; AAMA in urine: 800 ug/g",
    nioshRelTwa: 0.03,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 0.3,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "Ca [60 mg/m3]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes & skin; ataxia, numbness, paresthesia; muscle weakness, absent deep tendon reflex; lassitude; tremor; repro effects; [carcinogen]",
    targetOrgans: "Eyes, skin, CNS, PNS, reproductive system",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acrylic acid",
    synonyms: "2-Propenoic acid, Acroleic acid, Vinylformic acid",
    cas: "79-10-7",
    rtecs: "AS4375000",
    dot: "2218 132P",
    formula: "CH2=CHCOOH",
    mw: 72.06,
    bp: "286°F (141°C)",
    vp20: 3.1,
    density: 1.05,
    flp: "121°F (49.4°C)",
    lel: 2.4,
    uel: 8.0,
    acgihTlvTwa: 2,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A4",
    acgihTlvBasis: "URT irr",
    acgihBei: null,
    nioshRelTwa: 2,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "N.D.",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, respiratory system; eye and skin burns; skin sensitization; in animals: lung, liver, kidney injury",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "Chemical cartridge / Supplied air",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Acrylonitrile",
    synonyms: "Vinyl cyanide, 2-Propenenitrile, Cyanoethylene",
    cas: "107-13-1",
    rtecs: "AT5250000",
    dot: "1093 131P",
    formula: "CH2=CHCN",
    mw: 53.05,
    bp: "171°F (77.3°C)",
    vp20: 83,
    density: 0.81,
    flp: "30°F (-1°C)",
    lel: 3.0,
    uel: 17.0,
    acgihTlvTwa: 2,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A3 (Confirmed Animal Carcinogen)",
    acgihTlvBasis: "CNS impair; LRT irr",
    acgihBei: null,
    nioshRelTwa: 1,
    nioshRelStel: null,
    nioshRelC: 10,
    nioshCa: true,
    oshaPelTwa: 2,
    oshaPelStel: null,
    oshaPelC: 10,
    idlh: "Ca [85 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes & skin; asphyxia; headache, sneezing, nausea, vomiting; dizziness, weakness; convulsions; [carcinogen]",
    targetOrgans: "Eyes, skin, cardiovascular system, liver, kidneys, CNS",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Water wash immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Allyl alcohol",
    synonyms: "2-Propen-1-ol, Vinyl carbinol",
    cas: "107-18-6",
    rtecs: "BA5075000",
    dot: "1098 131",
    formula: "CH2=CHCH2OH",
    mw: 58.08,
    bp: "205°F (96.9°C)",
    vp20: 17.0,
    density: 0.85,
    flp: "70°F (21°C)",
    lel: 2.5,
    uel: 18.0,
    acgihTlvTwa: 0.5,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A4",
    acgihTlvBasis: "Eye & URT irr",
    acgihBei: null,
    nioshRelTwa: 2,
    nioshRelStel: 4,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 2,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "20 ppm",
    routes: "Inhalation, Ingestion, Skin absorption, Contact",
    symptoms: "Irritation of eyes, tissue damage; irritation of upper respiratory system, skin; pulmonary edema",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "20 ppm: Sa:Cf/PaprOv/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Allyl chloride",
    synonyms: "3-Chloropropene, 1-Chloro-2-propene",
    cas: "107-05-1",
    rtecs: "UC7350000",
    dot: "1100 131",
    formula: "CH2=CHCH2Cl",
    mw: 76.50,
    bp: "113°F (45°C)",
    vp20: 295,
    density: 0.94,
    flp: "-25°F (-31.7°C)",
    lel: 2.9,
    uel: 11.1,
    acgihTlvTwa: 1,
    acgihTlvStel: 2,
    acgihTlvC: null,
    acgihNotations: "Skin; A3",
    acgihTlvBasis: "Eye & URT irr; liver & kidney dam",
    acgihBei: null,
    nioshRelTwa: 1,
    nioshRelStel: 2,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 1,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "250 ppm",
    routes: "Inhalation, Ingestion, Skin absorption, Contact",
    symptoms: "Irritation of eyes, skin, nose; pulmonary edema; in animals: liver and kidney injury",
    targetOrgans: "Eyes, skin, respiratory system, liver, kidneys",
    respirator: "25 ppm: Sa:Cf; 50 ppm: ScbaF/SaF; 250 ppm: SaF:Pd,Pp",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Ammonia",
    synonyms: "Anhydrous ammonia, Aqua ammonia",
    cas: "7664-41-7",
    rtecs: "BO0875000",
    dot: "1005 125",
    formula: "NH3",
    mw: 17.03,
    bp: "-28°F (-33.3°C)",
    vp20: 6460, // gas at room temp (8.5 atm)
    density: 0.60, // gas relative to air
    flp: "NA (Gas)",
    lel: 15.0,
    uel: 28.0,
    acgihTlvTwa: 25,
    acgihTlvStel: 35,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "Eye dam; URT irr",
    acgihBei: null,
    nioshRelTwa: 25,
    nioshRelStel: 35,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 50,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "300 ppm",
    routes: "Inhalation, Contact",
    symptoms: "Irritation of eyes, nose, throat; dyspnea, wheezing, chest pain; pulmonary edema; pink frothy sputum; skin burns, vesication; liquid: frostbite",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "250 ppm: CcrS/Sa; 300 ppm: Sa:Cf/PaprS/CcrFS/GmFS/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support"
  },
  {
    name: "Aniline",
    synonyms: "Aminobenzene, Phenylamine, Benzenamine",
    cas: "62-53-3",
    rtecs: "BW6650000",
    dot: "1547 153",
    formula: "C6H5NH2",
    mw: 93.13,
    bp: "363°F (184°C)",
    vp20: 0.6,
    density: 1.02,
    flp: "158°F (70°C)",
    lel: 1.3,
    uel: 11.0,
    acgihTlvTwa: 2,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A3 (Animal Carcinogen); BEI",
    acgihTlvBasis: "MetHb-emia",
    acgihBei: "Aniline in urine: 0.5 mg/L, End of shift",
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 5,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "Ca [100 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Headache, lassitude, dizziness; cyanosis; ataxia; dyspnea; anorexia, nausea, vomiting; [carcinogen]",
    targetOrgans: "Blood, CVS, liver, kidneys, skin",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash promptly; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Benzene",
    synonyms: "Benzol, Phenyl hydride, Coal naphtha",
    cas: "71-43-2",
    rtecs: "CY1400000",
    dot: "1114 130",
    formula: "C6H6",
    mw: 78.11,
    bp: "176°F (80.1°C)",
    vp20: 75.2,
    density: 0.879,
    flp: "12°F (-11°C)",
    lel: 1.2,
    uel: 7.8,
    acgihTlvTwa: 0.02, // Updated in 2025 ACGIH TLVs!
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A1 (Confirmed Human Carcinogen); BEI",
    acgihTlvBasis: "Myelodysplastic syndrome; acute myeloid leukemia; chromosomal damage",
    acgihBei: "S-Phenylmercapturic acid in urine: 25 ug/g creatinine; t,t-Muconic acid in urine: 500 ug/g creatinine",
    nioshRelTwa: 0.1,
    nioshRelStel: 1.0,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 1,
    oshaPelStel: 5,
    oshaPelC: null,
    idlh: "Ca [500 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, nose, respiratory system; dizziness; headache, nausea, staggered gait; anorexia, lassitude; bone marrow depression; leukemia",
    targetOrgans: "Eyes, skin, respiratory system, blood, CNS, bone marrow",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash promptly; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "1-Butanol (n-Butanol)",
    synonyms: "Butyl alcohol, 1-Hydroxybutane, Propylcarbinol",
    cas: "71-36-3",
    rtecs: "EO1400000",
    dot: "1120 129",
    formula: "CH3(CH2)3OH",
    mw: 74.12,
    bp: "243°F (117.7°C)",
    vp20: 5.5,
    density: 0.810,
    flp: "84°F (28.9°C)",
    lel: 1.4,
    uel: 11.2,
    acgihTlvTwa: 20,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "Eye & URT irr",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: 50,
    nioshCa: false,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "1400 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, nose, throat; headache, dizziness, drowsiness; corneal inflammation, blurred vision, photophobia; dermatitis",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "1250 ppm: Sa:Cf/PaprOv; 1400 ppm: CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "2-Butanol (sec-Butanol)",
    synonyms: "sec-Butyl alcohol, 2-Hydroxybutane, Methyl ethyl carbinol",
    cas: "78-92-2",
    rtecs: "EO1750000",
    dot: "1120 129",
    formula: "CH3CH(OH)CH2CH3",
    mw: 74.12,
    bp: "211°F (99.5°C)",
    vp20: 12.5,
    density: 0.806,
    flp: "75°F (24°C)",
    lel: 1.7,
    uel: 9.8,
    acgihTlvTwa: 100,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "URT irr; CNS impair",
    acgihBei: null,
    nioshRelTwa: 100,
    nioshRelStel: 150,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 150,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "2000 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, nose, throat; narcosis; dizziness, drowsiness",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "1000 ppm: CcrOv/Sa; 2000 ppm: Sa:Cf/PaprOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "tert-Butanol",
    synonyms: "tert-Butyl alcohol, 2-Methyl-2-propanol, Trimethyl carbinol",
    cas: "75-65-0",
    rtecs: "EO1925000",
    dot: "1120 129",
    formula: "(CH3)3COH",
    mw: 74.12,
    bp: "180°F (82.4°C)",
    vp20: 31.0,
    density: 0.786,
    flp: "52°F (11°C)",
    lel: 2.4,
    uel: 8.0,
    acgihTlvTwa: 100,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "A4",
    acgihTlvBasis: "CNS impair",
    acgihBei: null,
    nioshRelTwa: 100,
    nioshRelStel: 150,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "1600 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, nose, throat; drowsiness, dizziness, headache; narcosis",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "1600 ppm: Sa:Cf/PaprOv/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "n-Butyl acetate",
    synonyms: "Butyl ethanoate, Acetic acid butyl ester",
    cas: "123-86-4",
    rtecs: "AF7350000",
    dot: "1123 129",
    formula: "CH3COO(CH2)3CH3",
    mw: 116.16,
    bp: "258°F (126°C)",
    vp20: 11.5,
    density: 0.882,
    flp: "72°F (22°C)",
    lel: 1.7,
    uel: 7.6,
    acgihTlvTwa: 50,
    acgihTlvStel: 150,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "Eye & URT irr",
    acgihBei: null,
    nioshRelTwa: 150,
    nioshRelStel: 200,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 150,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "1700 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, upper respiratory system; headache, drowsiness, narcosis",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "1500 ppm: CcrOv/Sa; 1700 ppm: Sa:Cf/PaprOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "n-Butyl acrylate",
    synonyms: "Butyl 2-propenoate, Acrylic acid butyl ester",
    cas: "141-32-2",
    rtecs: "UD3150000",
    dot: "2348 130P",
    formula: "CH2=CHCOOCH2(CH2)2CH3",
    mw: 128.17,
    bp: "293°F (145°C)",
    vp20: 4.0,
    density: 0.89,
    flp: "103°F (39.4°C)",
    lel: 1.5,
    uel: 9.9,
    acgihTlvTwa: 2,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "DSEN; A4",
    acgihTlvBasis: "Irr (Eye, skin, URT)",
    acgihBei: null,
    nioshRelTwa: 10,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "N.D.",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, upper respiratory system; sensitization; in animals: dyspnea",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "Supplied air / chemical cartridge",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Carbon dioxide",
    synonyms: "Carbonic acid gas, Dry ice",
    cas: "124-38-9",
    rtecs: "FF6400000",
    dot: "1013 120; 1845 120 (dry ice)",
    formula: "CO2",
    mw: 44.01,
    bp: "-109°F (-78.5°C, sublimes)",
    vp20: 42900, // gas (56.5 atm)
    density: 1.53, // relative to air
    flp: "NA (Gas)",
    lel: null,
    uel: null,
    acgihTlvTwa: 5000,
    acgihTlvStel: 30000,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "Asphyxia",
    acgihBei: null,
    nioshRelTwa: 5000,
    nioshRelStel: 30000,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 5000,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "40,000 ppm",
    routes: "Inhalation, Contact (dry ice)",
    symptoms: "Headache, dizziness, restlessness; paresthesias; dyspnea; sweating, malaise; tachycardia, elevated BP; coma, asphyxiation; frostbite",
    targetOrgans: "Respiratory system, cardiovascular system",
    respirator: "40,000 ppm: Sa/ScbaF",
    firstAid: "Eye: Frostbite wash; Skin: Frostbite treatment; Breath: Fresh air"
  },
  {
    name: "Carbon disulfide",
    synonyms: "Carbon bisulfide, Dithiocarbonic anhydride",
    cas: "75-15-0",
    rtecs: "FF6650000",
    dot: "1131 131",
    formula: "CS2",
    mw: 76.14,
    bp: "116°F (46.3°C)",
    vp20: 297,
    density: 1.26,
    flp: "-22°F (-30°C)",
    lel: 1.3,
    uel: 50.0,
    acgihTlvTwa: 1,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A4; BEI",
    acgihTlvBasis: "PNS impair",
    acgihBei: "2-Thioxothiazolidine-4-carboxylic acid (TTCA) in urine: 0.5 mg/g creatinine, End of shift",
    nioshRelTwa: 1,
    nioshRelStel: 10,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 20,
    oshaPelStel: null,
    oshaPelC: 30,
    idlh: "500 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Dizziness, headache, poor sleep, lassitude, anxiety, anorexia, weight loss; psychosis; polyneuropathy; Parkinson-like syndrome; ocular changes; coronary heart disease; gastritis; kidney, liver injury",
    targetOrgans: "CNS, PNS, CVS, eyes, kidneys, liver, skin, repro system",
    respirator: "10 ppm: CcrOv/Sa; 25 ppm: Sa:Cf/PaprOv; 50 ppm: CcrFOv/GmFOv/PaprTOv/ScbaF/SaF; 500 ppm: Sa:Pd,Pp",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Carbon monoxide",
    synonyms: "Carbon oxide, Flue gas, Monoxide",
    cas: "630-08-0",
    rtecs: "FG3500000",
    dot: "1016 119",
    formula: "CO",
    mw: 28.01,
    bp: "-313°F (-191.4°C)",
    vp20: 35000,
    density: 0.97,
    flp: "Flammable Gas",
    lel: 12.5,
    uel: 74.0,
    acgihTlvTwa: 25, // Notice of Intended Change: 15 ppm
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "OTO; BEI",
    acgihTlvBasis: "COHb-emia; cardiovascular system impair; ototoxicity; headache",
    acgihBei: "Carboxyhemoglobin in blood: 3.5%; Carbon monoxide in end-exhaled air: 20 ppm",
    nioshRelTwa: 35,
    nioshRelStel: null,
    nioshRelC: 200,
    nioshCa: false,
    oshaPelTwa: 50,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "1200 ppm",
    routes: "Inhalation",
    symptoms: "Headache, tachypnea, nausea, weakness, dizziness, confusion, hallucination; cyanosis; depressed S-T segment; syncope, convulsions, coma",
    targetOrgans: "CVS, lungs, blood, CNS",
    respirator: "350 ppm: Sa; 875 ppm: Sa:Cf; 1200 ppm: GmFS/ScbaF/SaF",
    firstAid: "Breath: Resp support / 100% O2"
  },
  {
    name: "Carbon tetrachloride",
    synonyms: "Tetrachloromethane, Carbon tet, Freon 10, Halon 104",
    cas: "56-23-5",
    rtecs: "FG4900000",
    dot: "1846 151",
    formula: "CCl4",
    mw: 153.82,
    bp: "170°F (76.7°C)",
    vp20: 91.3,
    density: 1.594,
    flp: "None",
    lel: null,
    uel: null,
    acgihTlvTwa: 5,
    acgihTlvStel: 10,
    acgihTlvC: null,
    acgihNotations: "Skin; A2 (Suspected Human Carcinogen)",
    acgihTlvBasis: "Liver dam",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: 2,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 10,
    oshaPelStel: null,
    oshaPelC: 25,
    idlh: "Ca [200 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin; CNS depression; nausea, vomiting; liver & kidney damage; dizziness, incoordination; [carcinogen]",
    targetOrgans: "CNS, eyes, lungs, liver, kidneys, skin",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash promptly; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Chlorine",
    synonyms: "Molecular chlorine",
    cas: "7782-50-5",
    rtecs: "FO2100000",
    dot: "1017 124",
    formula: "Cl2",
    mw: 70.91,
    bp: "-29°F (-34°C)",
    vp20: 5168, // gas (6.8 atm)
    density: 2.47,
    flp: "Nonflammable Gas",
    lel: null,
    uel: null,
    acgihTlvTwa: 0.1,
    acgihTlvStel: 0.4,
    acgihTlvC: null,
    acgihNotations: "A4",
    acgihTlvBasis: "Resp tract irr; airway hyper-reactivity; pulm edema",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: 0.5,
    nioshCa: false,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: 1,
    idlh: "10 ppm",
    routes: "Inhalation, Contact",
    symptoms: "Burning of eyes, nose, mouth; lacrimation; rhinorrhea; cough, choking, substernal pain; nausea, vomiting; headache, dizziness; syncope; pulmonary edema; frostbite",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "5 ppm: CcrS/Sa; 10 ppm: Sa:Cf/PaprS/CcrFS/GmFS/ScbaF/SaF",
    firstAid: "Eye: Frostbite wash / Irrigate immediately; Skin: Frostbite treatment; Breath: Resp support"
  },
  {
    name: "Chloroform",
    synonyms: "Trichloromethane, Formyl trichloride, Methane trichloride",
    cas: "67-66-3",
    rtecs: "FS9100000",
    dot: "1888 151",
    formula: "CHCl3",
    mw: 119.38,
    bp: "143°F (61.7°C)",
    vp20: 160.0,
    density: 1.489,
    flp: "None",
    lel: null,
    uel: null,
    acgihTlvTwa: 10,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "A3 (Animal Carcinogen)",
    acgihTlvBasis: "Liver & embryo/fetal dam; CNS impair",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: 2,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: 50,
    idlh: "Ca [500 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin; dizziness, mental dullness, nausea, confusion; headache, lassitude; anesthesia; hepatomegaly; [carcinogen]",
    targetOrgans: "Liver, kidneys, heart, eyes, skin, CNS",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Cyclohexane",
    synonyms: "Hexahydrobenzene, Hexamethylene, Hexanaphthene",
    cas: "110-82-7",
    rtecs: "GU6300000",
    dot: "1145 128",
    formula: "C6H12",
    mw: 84.16,
    bp: "177°F (80.7°C)",
    vp20: 77.5,
    density: 0.779,
    flp: "-4°F (-20°C)",
    lel: 1.3,
    uel: 8.0,
    acgihTlvTwa: 100,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "BEI",
    acgihTlvBasis: "CNS impair; eye & URT irr",
    acgihBei: "1,2-Cyclohexanediol in urine: 50 mg/g creatinine, End of shift end of workweek",
    nioshRelTwa: 300,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 300,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "1300 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, respiratory system; drowsiness, dizziness; narcosis, coma",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "1300 ppm: Sa:Cf/PaprOv/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Cyclohexanol",
    synonyms: "Hexahydrophenol, Cyclohexyl alcohol, Hydrophenol",
    cas: "108-93-0",
    rtecs: "GV7875000",
    dot: "1993 128",
    formula: "C6H11OH",
    mw: 100.16,
    bp: "322°F (161°C)",
    vp20: 1.0,
    density: 0.96,
    flp: "154°F (67.8°C)",
    lel: 1.2,
    uel: null,
    acgihTlvTwa: 50,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; BEI",
    acgihTlvBasis: "Eye irr; CNS impair",
    acgihBei: "Cyclohexanol in urine: with hydrolysis, End of shift at end of workweek",
    nioshRelTwa: 50,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 50,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "400 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, nose, throat; narcosis; in animals: liver, kidney damage",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "400 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irr prompt; Skin: Water wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Cyclohexanone",
    synonyms: "Pimelic ketone, Ketohexamethylene, Anone",
    cas: "108-94-1",
    rtecs: "GW1050000",
    dot: "1915 127",
    formula: "C6H10O",
    mw: 98.14,
    bp: "312°F (155.6°C)",
    vp20: 5.0,
    density: 0.95,
    flp: "111°F (43.9°C)",
    lel: 1.1,
    uel: 9.4,
    acgihTlvTwa: 20,
    acgihTlvStel: 50,
    acgihTlvC: null,
    acgihNotations: "Skin; A3; BEI",
    acgihTlvBasis: "Eye & URT irr",
    acgihBei: "1,2-Cyclohexanediol in urine: 80 mg/L; Cyclohexanol in urine: 8 mg/L",
    nioshRelTwa: 25,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 50,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "700 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, mucous membranes; headache; narcosis, coma; dermatitis; in animals: liver, kidney damage",
    targetOrgans: "Eyes, skin, respiratory system, CNS, liver, kidneys",
    respirator: "625 ppm: Sa:Cf/PaprOv; 700 ppm: CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Dichloromethane (Methylene chloride)",
    synonyms: "Methylene chloride, DCM, Methylene bichloride",
    cas: "75-09-2",
    rtecs: "PA8050000",
    dot: "1593 160",
    formula: "CH2Cl2",
    mw: 84.93,
    bp: "104°F (39.8°C)",
    vp20: 350.0,
    density: 1.326,
    flp: "None",
    lel: 13.0,
    uel: 23.0,
    acgihTlvTwa: 50,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "A3 (Animal Carcinogen); BEI",
    acgihTlvBasis: "COHb-emia; CNS impair",
    acgihBei: "Dichloromethane in urine: 0.3 mg/L, End of shift",
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 25,
    oshaPelStel: 125,
    oshaPelC: null,
    idlh: "Ca [2300 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin; lassitude, drowsiness, dizziness; numbness, tingling limbs; nausea; CVS effects, elevated carboxyhemoglobin; [carcinogen]",
    targetOrgans: "Eyes, skin, CVS, CNS",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Diethyl ether",
    synonyms: "Ethyl ether, Ether, Ethoxyethane, Diethyl oxide",
    cas: "60-29-7",
    rtecs: "KI5775000",
    dot: "1155 127",
    formula: "C2H5OC2H5",
    mw: 74.12,
    bp: "94°F (34.6°C)",
    vp20: 442.0,
    density: 0.713,
    flp: "-49°F (-45°C)",
    lel: 1.9,
    uel: 36.0,
    acgihTlvTwa: 400,
    acgihTlvStel: 500,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "CNS impair; URT irr",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 400,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "1900 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, upper respiratory system; dizziness, drowsiness; narcosis; nausea, vomiting",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "1900 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irr prompt; Skin: Water wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Diethylamine",
    synonyms: "N,N-Diethylamine, N-Ethylethanamine",
    cas: "109-89-7",
    rtecs: "HZ8750000",
    dot: "1154 132",
    formula: "(C2H5)2NH",
    mw: 73.14,
    bp: "132°F (55.5°C)",
    vp20: 192.0,
    density: 0.71,
    flp: "-15°F (-26°C)",
    lel: 1.8,
    uel: 10.1,
    acgihTlvTwa: 5,
    acgihTlvStel: 15,
    acgihTlvC: null,
    acgihNotations: "Skin; A4",
    acgihTlvBasis: "URT, eye, & skin irr",
    acgihBei: null,
    nioshRelTwa: 10,
    nioshRelStel: 25,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 25,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "200 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, respiratory system; skin burns; corneal edema; in animals: myocardial degeneration",
    targetOrgans: "Eyes, skin, respiratory system, CVS",
    respirator: "200 ppm: Sa:Cf/PaprS/CcrFS/GmFS/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Dimethylformamide (DMF)",
    synonyms: "N,N-Dimethylformamide, Formdimethylamide",
    cas: "68-12-2",
    rtecs: "LQ2100000",
    dot: "2265 129",
    formula: "HCON(CH3)2",
    mw: 73.10,
    bp: "307°F (153°C)",
    vp20: 3.0,
    density: 0.95,
    flp: "136°F (57.8°C)",
    lel: 2.2,
    uel: 15.2,
    acgihTlvTwa: 5,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A3 (Animal Carcinogen); BEI",
    acgihTlvBasis: "Liver dam; eye & URT irr",
    acgihBei: "Total N-Methylformamide in urine: 30 mg/L; N-Acetyl-S-(N-methylcarbamoyl)cysteine in urine: 30 mg/L",
    nioshRelTwa: 10,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 10,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "500 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, respiratory system; nausea, vomiting, abdominal colic; liver damage, hepatomegaly, jaundice",
    targetOrgans: "Eyes, skin, respiratory system, liver, kidneys, CVS",
    respirator: "100 ppm: Sa; 250 ppm: Sa:Cf; 500 ppm: SaT:Cf/ScbaF/SaF",
    firstAid: "Eye: Irr prompt; Skin: Water flush prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "1,4-Dioxane",
    synonyms: "Diethylene dioxide, 1,4-Diethylene oxide, Dioxan",
    cas: "123-91-1",
    rtecs: "JG8225000",
    dot: "1165 127",
    formula: "C4H8O2",
    mw: 88.11,
    bp: "214°F (101°C)",
    vp20: 29.0,
    density: 1.033,
    flp: "54°F (12°C)",
    lel: 2.0,
    uel: 22.0,
    acgihTlvTwa: 20,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; A3 (Animal Carcinogen)",
    acgihTlvBasis: "Liver dam",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: 1,
    nioshCa: true,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "Ca [500 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, nose, throat; drowsiness, headache; nausea, vomiting; liver & kidney damage; [carcinogen]",
    targetOrgans: "Eyes, skin, respiratory system, liver, kidneys",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Water wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Ethanol (Ethyl alcohol)",
    synonyms: "Ethyl alcohol, Grain alcohol, Cologne spirit",
    cas: "64-17-5",
    rtecs: "KQ6300000",
    dot: "1170 127",
    formula: "C2H5OH",
    mw: 46.07,
    bp: "173°F (78.3°C)",
    vp20: 44.0,
    density: 0.789,
    flp: "55°F (12.8°C)",
    lel: 3.3,
    uel: 19.0,
    acgihTlvTwa: null,
    acgihTlvStel: 1000,
    acgihTlvC: null,
    acgihNotations: "A3",
    acgihTlvBasis: "URT irr",
    acgihBei: null,
    nioshRelTwa: 1000,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 1000,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "3300 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, nose; headache, drowsiness, lassitude, narcosis; cough; liver damage; anemia",
    targetOrgans: "Eyes, skin, respiratory system, CNS, liver, blood",
    respirator: "3300 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irr prompt; Skin: Water flush prompt; Breath: Fresh air"
  },
  {
    name: "Ethyl acetate",
    synonyms: "Acetic acid ethyl ester, Ethyl ethanoate",
    cas: "141-78-6",
    rtecs: "AH5425000",
    dot: "1173 129",
    formula: "CH3COOC2H5",
    mw: 88.11,
    bp: "171°F (77.1°C)",
    vp20: 73.0,
    density: 0.902,
    flp: "24°F (-4.4°C)",
    lel: 2.0,
    uel: 11.5,
    acgihTlvTwa: 400,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "URT & eye irr",
    acgihBei: null,
    nioshRelTwa: 400,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 400,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "2000 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, nose, throat; narcosis; dermatitis",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "2000 ppm: Sa:Cf/PaprOv/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irr prompt; Skin: Water flush prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Ethylbenzene",
    synonyms: "Ethylbenzol, Phenylethane",
    cas: "100-41-4",
    rtecs: "DA0700000",
    dot: "1175 130",
    formula: "C6H5C2H5",
    mw: 106.17,
    bp: "277°F (136°C)",
    vp20: 7.1,
    density: 0.867,
    flp: "55°F (12.8°C)",
    lel: 0.8,
    uel: 6.7,
    acgihTlvTwa: 20,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "OTO (Ototoxicant); A3; BEI",
    acgihTlvBasis: "URT & eye irr; ototoxicity; kidney eff; CNS impair",
    acgihBei: "Sum of mandelic acid and phenylglyoxylic acid in urine: 150 mg/g creatinine, End of shift",
    nioshRelTwa: 100,
    nioshRelStel: 125,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "800 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, mucous membranes; headache; dermatitis; narcosis, coma",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "800 ppm: CcrOv/GmFOv/PaprTOv/Sa/ScbaF",
    firstAid: "Eye: Irr prompt; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Ethylene glycol",
    synonyms: "1,2-Ethanediol, Glycol alcohol, Antifreeze",
    cas: "107-21-1",
    rtecs: "KW2975000",
    dot: "",
    formula: "HOCH2CH2OH",
    mw: 62.07,
    bp: "388°F (197.6°C)",
    vp20: 0.06,
    density: 1.11,
    flp: "232°F (111°C)",
    lel: 3.2,
    uel: 15.3,
    acgihTlvTwa: 25, // ppm (vapor)
    acgihTlvStel: 50, // ppm (vapor) / 10 mg/m3 (inhalable)
    acgihTlvC: null,
    acgihNotations: "A4",
    acgihTlvBasis: "URT irr",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "N.D.",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, nose, throat; nausea, vomiting, abdominal pain; lassitude, stupor, convulsions, CNS depression",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "Supplied air / particulate & organic vapor",
    firstAid: "Eye: Irr prompt; Skin: Water wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Formaldehyde",
    synonyms: "Formalin, Methanal, Methylene oxide",
    cas: "50-00-0",
    rtecs: "LP8925000",
    dot: "1198 132; 2209 132",
    formula: "HCHO",
    mw: 30.03,
    bp: "-6°F (-21°C)",
    vp20: 3260, // gas at room temp
    density: 0.815,
    flp: "140°F (60°C, 37% formalin)",
    lel: 7.0,
    uel: 73.0,
    acgihTlvTwa: 0.1,
    acgihTlvStel: 0.3,
    acgihTlvC: null,
    acgihNotations: "DSEN; RSEN; A1 (Confirmed Human Carcinogen)",
    acgihTlvBasis: "URT & eye irr; URT cancer",
    acgihBei: null,
    nioshRelTwa: 0.016,
    nioshRelStel: null,
    nioshRelC: 0.1,
    nioshCa: true,
    oshaPelTwa: 0.75,
    oshaPelStel: 2.0,
    oshaPelC: null,
    idlh: "Ca [20 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, nose, throat; respiratory sensitization; lacrimation; cough; bronchospasm; nasal cancer",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "n-Heptane",
    synonyms: "Heptane, Dipropylmethane",
    cas: "142-82-5",
    rtecs: "MI7700000",
    dot: "1206 128",
    formula: "CH3(CH2)5CH3",
    mw: 100.20,
    bp: "209°F (98.4°C)",
    vp20: 35.5,
    density: 0.684,
    flp: "25°F (-3.9°C)",
    lel: 1.05,
    uel: 6.7,
    acgihTlvTwa: 200, // Adopted 2025: straight and branched isomers 200 ppm
    acgihTlvStel: 400,
    acgihTlvC: null,
    acgihNotations: "OTO (Ototoxicant)",
    acgihTlvBasis: "URT irr; lung dam; CNS impair; ototoxicity",
    acgihBei: "2,5-Heptanedione in urine: 140 ug/L, End of exposure",
    nioshRelTwa: 85,
    nioshRelStel: null,
    nioshRelC: 440,
    nioshCa: false,
    oshaPelTwa: 500,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "750 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Dizziness, stupor, incoordination; loss of appetite, nausea; dermatitis; chemical pneumonitis",
    targetOrgans: "Skin, respiratory system, CNS",
    respirator: "750 ppm: CcrOv/GmFOv/PaprOv/Sa/ScbaF",
    firstAid: "Eye: Irr prompt; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "n-Hexane",
    synonyms: "Hexane, Hexyl hydride",
    cas: "110-54-3",
    rtecs: "MN9275000",
    dot: "1208 128",
    formula: "CH3(CH2)4CH3",
    mw: 86.18,
    bp: "156°F (68.7°C)",
    vp20: 121.0,
    density: 0.655,
    flp: "-7°F (-21.7°C)",
    lel: 1.1,
    uel: 7.5,
    acgihTlvTwa: 50,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "Skin; BEI",
    acgihTlvBasis: "CNS impair; peripheral neuropathy; eye irr",
    acgihBei: "2,5-Hexanedione in urine: 0.5 mg/L, End of shift",
    nioshRelTwa: 50,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 500,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "1100 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin absorption, Contact",
    symptoms: "Irritation of eyes, nose; dizziness; peripheral neuropathy (numbness of toes/fingers, weakness); muscle weakness; anorexia",
    targetOrgans: "Eyes, skin, respiratory system, CNS, PNS",
    respirator: "500 ppm: Sa; 1100 ppm: Sa:Cf/ScbaF/SaF",
    firstAid: "Eye: Irr prompt; Skin: Soap wash promptly; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Hydrogen cyanide",
    synonyms: "Hydrocyanic acid, Prussic acid, Formonitrile",
    cas: "74-90-8",
    rtecs: "MW6825000",
    dot: "1051 117 (>20%); 1613 154 (solution)",
    formula: "HCN",
    mw: 27.03,
    bp: "78°F (25.6°C)",
    vp20: 630,
    density: 0.69,
    flp: "0°F (-17.8°C)",
    lel: 5.6,
    uel: 40.0,
    acgihTlvTwa: null,
    acgihTlvStel: null,
    acgihTlvC: 4.7,
    acgihNotations: "Skin; BEI",
    acgihTlvBasis: "URT irr; headache; nausea; thyroid eff",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: 4.7,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 10,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "50 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Asphyxia; lassitude, headache, confusion; nausea, vomiting; slow gasping respiration; thyroid changes",
    targetOrgans: "CNS, CVS, liver, kidneys, thyroid",
    respirator: "47 ppm: Sa; 50 ppm: Sa:Cf/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Hydrogen sulfide",
    synonyms: "Hydrosulfuric acid, Sewer gas, Sulfuretted hydrogen",
    cas: "7783-06-4",
    rtecs: "MX1225000",
    dot: "1053 117",
    formula: "H2S",
    mw: 34.08,
    bp: "-76°F (-60°C)",
    vp20: 13300, // gas (17.6 atm)
    density: 1.19,
    flp: "Flammable Gas",
    lel: 4.0,
    uel: 44.0,
    acgihTlvTwa: 1,
    acgihTlvStel: 5,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "URT irr; CNS impair",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: 10,
    nioshCa: false,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: 20,
    idlh: "100 ppm",
    routes: "Inhalation, Contact",
    symptoms: "Irritation of eyes, respiratory system; apnea, coma, convulsions; conjunctivitis, eye pain, lacrimation; dizziness, headache; olfactory fatigue",
    targetOrgans: "Eyes, respiratory system, CNS",
    respirator: "100 ppm: PaprS/GmFS/Sa/ScbaF",
    firstAid: "Eye: Frostbite wash / Irrigate; Skin: Frostbite treatment; Breath: Resp support"
  },
  {
    name: "Isopropanol (IPA)",
    synonyms: "Isopropyl alcohol, 2-Propanol, Rubbing alcohol",
    cas: "67-63-0",
    rtecs: "NT8050000",
    dot: "1219 129",
    formula: "(CH3)2CHOH",
    mw: 60.10,
    bp: "181°F (82.6°C)",
    vp20: 33.0,
    density: 0.786,
    flp: "53°F (11.7°C)",
    lel: 2.0,
    uel: 12.7,
    acgihTlvTwa: 200,
    acgihTlvStel: 400,
    acgihTlvC: null,
    acgihNotations: "A4; BEI",
    acgihTlvBasis: "Eye & URT irr; CNS impair",
    acgihBei: "Acetone in urine: 40 mg/L, End of shift at end of workweek",
    nioshRelTwa: 400,
    nioshRelStel: 500,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 400,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "2000 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, nose, throat; drowsiness, dizziness, headache; dry cracking skin; narcosis",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "2000 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Methanol",
    synonyms: "Methyl alcohol, Wood alcohol, Carbinol",
    cas: "67-56-1",
    rtecs: "PC1400000",
    dot: "1230 131",
    formula: "CH3OH",
    mw: 32.04,
    bp: "147°F (64°C)",
    vp20: 96.0,
    density: 0.792,
    flp: "52°F (11°C)",
    lel: 6.0,
    uel: 36.0,
    acgihTlvTwa: 200,
    acgihTlvStel: 250,
    acgihTlvC: null,
    acgihNotations: "Skin; BEIc",
    acgihTlvBasis: "Headache; eye dam; dizziness; nausea",
    acgihBei: "Methanol in urine: 15 mg/L, End of shift",
    nioshRelTwa: 200,
    nioshRelStel: 250,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 200,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "6000 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, upper respiratory system; headache, drowsiness, dizziness, nausea, vomiting; visual disturbance (blindness); acidosis",
    targetOrgans: "Eyes, skin, respiratory system, CNS, GI tract",
    respirator: "2000 ppm: Sa; 5000 ppm: Sa:Cf; 6000 ppm: SaT:Cf/ScbaF/SaF",
    firstAid: "Eye: Irr prompt; Skin: Water flush prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Methyl ethyl ketone (MEK)",
    synonyms: "2-Butanone, Ethyl methyl ketone, Methyl acetone",
    cas: "78-93-3",
    rtecs: "EL6475000",
    dot: "1193 127",
    formula: "CH3COCH2CH3",
    mw: 72.11,
    bp: "175°F (79.6°C)",
    vp20: 77.5,
    density: 0.805,
    flp: "16°F (-9°C)",
    lel: 1.4,
    uel: 11.4,
    acgihTlvTwa: 75, // Updated in 2025 ACGIH!
    acgihTlvStel: 150,
    acgihTlvC: null,
    acgihNotations: "Skin; BEI",
    acgihTlvBasis: "Embryo/fetal dam; URT irr; headache; dizziness",
    acgihBei: "Methyl ethyl ketone in urine: 2 mg/L, End of shift",
    nioshRelTwa: 200,
    nioshRelStel: 300,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 200,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "3000 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, nose; headache; dizziness; vomiting; dermatitis; narcosis",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "3000 ppm: Sa:Cf/PaprOv/CcrFOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water wash immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Methyl isobutyl ketone (MIBK)",
    synonyms: "Hexone, 4-Methyl-2-pentanone, Isopropylacetone",
    cas: "108-10-1",
    rtecs: "SA9275000",
    dot: "1245 127",
    formula: "CH3COCH2CH(CH3)2",
    mw: 100.16,
    bp: "242°F (117°C)",
    vp20: 16.0,
    density: 0.801,
    flp: "64°F (18°C)",
    lel: 1.2,
    uel: 8.0,
    acgihTlvTwa: 20,
    acgihTlvStel: 75,
    acgihTlvC: null,
    acgihNotations: "A3 (Animal Carcinogen); BEI",
    acgihTlvBasis: "URT irr; dizziness; headache",
    acgihBei: "Methyl isobutyl ketone in urine: 1 mg/L, End of shift",
    nioshRelTwa: 50,
    nioshRelStel: 75,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "500 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, mucous membranes; headache, narcosis, coma; dermatitis; in animals: liver, kidney damage",
    targetOrgans: "Eyes, skin, respiratory system, CNS, liver, kidneys",
    respirator: "500 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irr prompt; Skin: Water flush prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Nitric acid",
    synonyms: "Aqua fortis, Engravers acid, Hydrogen nitrate",
    cas: "7697-37-2",
    rtecs: "QU5775000",
    dot: "2031 157 (fuming); 2032 157 (>70%)",
    formula: "HNO3",
    mw: 63.02,
    bp: "181°F (83°C)",
    vp20: 48.0,
    density: 1.50,
    flp: "Noncombustible Liquid",
    lel: null,
    uel: null,
    acgihTlvTwa: 2, // Notice of Intended Change (NIC): 0.025 ppm (IFV)
    acgihTlvStel: 4,
    acgihTlvC: null,
    acgihNotations: "",
    acgihTlvBasis: "URT & eye irr; dental erosion",
    acgihBei: null,
    nioshRelTwa: 2,
    nioshRelStel: 4,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 2,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "25 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, skin, mucous membranes; delayed pulmonary edema; pneumonitis, bronchitis; dental erosion",
    targetOrgans: "Eyes, skin, respiratory system, teeth",
    respirator: "25 ppm: Sa:Cf/CcrFS/GmFS/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Nitrogen dioxide",
    synonyms: "Dinitrogen tetroxide, Nitrogen peroxide",
    cas: "10102-44-0",
    rtecs: "QW9800000",
    dot: "1067 124",
    formula: "NO2",
    mw: 46.01,
    bp: "70°F (21.1°C)",
    vp20: 720,
    density: 1.44,
    flp: "Noncombustible Gas",
    lel: null,
    uel: null,
    acgihTlvTwa: 0.2,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "A4",
    acgihTlvBasis: "LRT irr",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: 1.0,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: 5,
    idlh: "20 ppm",
    routes: "Inhalation, Contact",
    symptoms: "Irritation of eyes, nose, throat; cough, mucoid frothy sputum, decreased pulmonary function; chronic bronchitis; pulmonary edema",
    targetOrgans: "Eyes, respiratory system, CVS",
    respirator: "20 ppm: Sa:Cf/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support"
  },
  {
    name: "Perchloroethylene",
    synonyms: "Tetrachloroethylene, Perk, PCE, Ethylene tetrachloride",
    cas: "127-18-4",
    rtecs: "KX3850000",
    dot: "1897 160",
    formula: "Cl2C=CCl2",
    mw: 165.83,
    bp: "250°F (121°C)",
    vp20: 14.0,
    density: 1.623,
    flp: "None",
    lel: null,
    uel: null,
    acgihTlvTwa: 25,
    acgihTlvStel: 100,
    acgihTlvC: null,
    acgihNotations: "A3 (Animal Carcinogen); BEI",
    acgihTlvBasis: "CNS impair",
    acgihBei: "Tetrachloroethylene in end-exhaled air: 3 ppm; in blood: 0.5 mg/L",
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: 200,
    idlh: "Ca [150 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, nose, throat, respiratory system; nausea; flushing face & neck; dizziness, incoordination, headache; liver damage; [carcinogen]",
    targetOrgans: "Eyes, skin, respiratory system, liver, kidneys, CNS",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Styrene",
    synonyms: "Ethenylbenzene, Vinylbenzene, Styrene monomer",
    cas: "100-42-5",
    rtecs: "WL3675000",
    dot: "2055 128P",
    formula: "C6H5CH=CH2",
    mw: 104.15,
    bp: "293°F (145°C)",
    vp20: 5.0,
    density: 0.906,
    flp: "88°F (31.1°C)",
    lel: 0.9,
    uel: 6.8,
    acgihTlvTwa: 10,
    acgihTlvStel: 20,
    acgihTlvC: null,
    acgihNotations: "OTO (Ototoxicant); A3; BEI",
    acgihTlvBasis: "CNS & hearing impair; peripheral neuropathy; visual disorders",
    acgihBei: "Mandelic acid plus phenylglyoxylic acid in urine: 150 mg/g; Styrene in urine: 20 ug/L",
    nioshRelTwa: 50,
    nioshRelStel: 100,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: 200,
    idlh: "700 ppm",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, nose, respiratory system; headache, lassitude, dizziness, confusion, drowsiness, unsteady gait; hearing loss; narcosis; defatting dermatitis",
    targetOrgans: "Eyes, skin, respiratory system, CNS, liver",
    respirator: "500 ppm: CcrOv/Sa; 700 ppm: Sa:Cf/PaprOv/GmFOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Sulfur dioxide",
    synonyms: "Sulfurous acid anhydride, Sulfur oxide",
    cas: "7446-09-5",
    rtecs: "WS4550000",
    dot: "1079 125",
    formula: "SO2",
    mw: 64.07,
    bp: "14°F (-10°C)",
    vp20: 2470, // gas (3.2 atm)
    density: 2.26,
    flp: "Nonflammable Gas",
    lel: null,
    uel: null,
    acgihTlvTwa: null,
    acgihTlvStel: 0.25,
    acgihTlvC: null,
    acgihNotations: "A4",
    acgihTlvBasis: "Pulm func; LRT irr",
    acgihBei: null,
    nioshRelTwa: 2,
    nioshRelStel: 5,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 5,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "100 ppm",
    routes: "Inhalation, Contact",
    symptoms: "Irritation of eyes, nose, throat; rhinorrhea; choking, cough; reflex bronchoconstriction; liquid: frostbite",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "20 ppm: CcrS/Sa; 50 ppm: Sa:Cf/PaprS; 100 ppm: CcrFS/GmFS/ScbaF/SaF",
    firstAid: "Eye: Frostbite wash / Irrigate; Skin: Frostbite treatment; Breath: Resp support"
  },
  {
    name: "Sulfuric acid",
    synonyms: "Battery acid, Hydrogen sulfate, Oil of vitriol",
    cas: "7664-93-9",
    rtecs: "WS5600000",
    dot: "1830 137; 1832 137 (spent)",
    formula: "H2SO4",
    mw: 98.08,
    bp: "554°F (290°C)",
    vp20: 0.001,
    density: 1.84,
    flp: "Noncombustible Liquid",
    lel: null,
    uel: null,
    acgihTlvTwa: 0.2, // mg/m3 (T - thoracic fraction)
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "A2 (M) (Carcinogenic inorganic mists)",
    acgihTlvBasis: "Pulm func",
    acgihBei: null,
    nioshRelTwa: 1.0,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 1.0,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "15 mg/m3",
    routes: "Inhalation, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, nose, throat; pulmonary edema, bronchitis; emphysema; conjunctivitis; dental erosion; skin burns",
    targetOrgans: "Eyes, skin, respiratory system, teeth",
    respirator: "15 mg/m3: GmFAg100/PaprTHie/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water flush immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Tetrahydrofuran (THF)",
    synonyms: "1,4-Epoxybutane, Diethylene oxide, Tetramethylene oxide",
    cas: "109-99-9",
    rtecs: "LU5950000",
    dot: "2056 127",
    formula: "C4H8O",
    mw: 72.11,
    bp: "151°F (66°C)",
    vp20: 143.0,
    density: 0.889,
    flp: "6°F (-14.4°C)",
    lel: 2.0,
    uel: 11.8,
    acgihTlvTwa: 50,
    acgihTlvStel: 100,
    acgihTlvC: null,
    acgihNotations: "Skin; A3; BEI",
    acgihTlvBasis: "URT irr; CNS impair; kidney dam",
    acgihBei: "Tetrahydrofuran in urine: 2 mg/L, End of shift",
    nioshRelTwa: 200,
    nioshRelStel: 250,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 200,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "2000 ppm [10% LEL]",
    routes: "Inhalation, Ingestion, Skin/Eye contact",
    symptoms: "Irritation of eyes, upper respiratory system; nausea, dizziness, headache; CNS depression",
    targetOrgans: "Eyes, skin, respiratory system, CNS",
    respirator: "2000 ppm: Sa:Cf/CcrFOv/GmFOv/PaprTOv/ScbaF/SaF",
    firstAid: "Eye: Irrigate immediately; Skin: Water wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Toluene",
    synonyms: "Methylbenzene, Toluol, Phenylmethane",
    cas: "108-88-3",
    rtecs: "XS5250000",
    dot: "1294 130",
    formula: "C6H5CH3",
    mw: 92.14,
    bp: "232°F (111°C)",
    vp20: 22.0,
    density: 0.867,
    flp: "40°F (4.4°C)",
    lel: 1.1,
    uel: 7.1,
    acgihTlvTwa: 20,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "OTO (Ototoxicant); A4; BEI",
    acgihTlvBasis: "CNS, visual, & hearing impair; female repro system eff; pregnancy loss",
    acgihBei: "Toluene in blood: 0.02 mg/L; o-Cresol in urine: 0.3 mg/g creatinine",
    nioshRelTwa: 100,
    nioshRelStel: 150,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 200,
    oshaPelStel: null,
    oshaPelC: 300,
    idlh: "500 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, nose; lassitude, confusion, euphoria, dizziness, headache; dilated pupils, lacrimation; hearing loss; insomnia; paresthesia",
    targetOrgans: "Eyes, skin, respiratory system, CNS, liver, kidneys",
    respirator: "500 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irr prompt; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Toluene-2,4-diisocyanate (TDI)",
    synonyms: "2,4-TDI, Diisocyanatoluene, Tolylene-2,4-diisocyanate",
    cas: "584-84-9",
    rtecs: "CZ6300000",
    dot: "2078 156",
    formula: "CH3C6H3(NCO)2",
    mw: 174.15,
    bp: "484°F (251°C)",
    vp20: 0.01,
    density: 1.22,
    flp: "260°F (127°C)",
    lel: 0.9,
    uel: 9.5,
    acgihTlvTwa: 0.001, // IFV
    acgihTlvStel: 0.005, // IFV
    acgihTlvC: null,
    acgihNotations: "Skin; DSEN; RSEN; A3; BEI",
    acgihTlvBasis: "Asthma; pulm func; eye irr",
    acgihBei: "Toluene diamine in urine: 5 ug/g creatinine, End of shift",
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: null,
    oshaPelStel: null,
    oshaPelC: 0.02,
    idlh: "Ca [2.5 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin, nose, throat; choke, paroxysmal cough; chest pain, retrosternal soreness; asthma, occupational asthma; pulmonary edema",
    targetOrgans: "Eyes, skin, respiratory system",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash immediately; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Trichloroethylene (TCE)",
    synonyms: "Trichloroethene, Ethylene trichloride, Trilene",
    cas: "79-01-6",
    rtecs: "KX4550000",
    dot: "1710 160",
    formula: "ClCH=CCl2",
    mw: 131.39,
    bp: "189°F (87°C)",
    vp20: 58.0,
    density: 1.464,
    flp: "None",
    lel: 8.0,
    uel: 10.5,
    acgihTlvTwa: 10,
    acgihTlvStel: 25,
    acgihTlvC: null,
    acgihNotations: "A2 (Suspected Human Carcinogen); BEI",
    acgihTlvBasis: "CNS impair; cognitive decrements; renal toxicity",
    acgihBei: "Trichloroacetic acid in urine: 15 mg/L; Trichloroethanol in blood: 0.5 mg/L",
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: 2,
    nioshCa: true,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: 200,
    idlh: "Ca [1000 ppm]",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, skin; headache, visual disturbance, lassitude, dizziness, tremor, somnolence; nausea, vomiting; cardiac arrhythmias; [carcinogen]",
    targetOrgans: "Eyes, skin, respiratory system, heart, liver, kidneys, CNS",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFOv/ScbaE",
    firstAid: "Eye: Irr prompt; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  },
  {
    name: "Vinyl chloride",
    synonyms: "Chloroethene, Chloroethylene, Vinyl chloride monomer (VCM)",
    cas: "75-01-4",
    rtecs: "KU9625000",
    dot: "1086 116P",
    formula: "CH2=CHCl",
    mw: 62.50,
    bp: "7°F (-13.9°C)",
    vp20: 2530, // gas (3.3 atm)
    density: 0.91,
    flp: "-108°F (-78°C)",
    lel: 3.6,
    uel: 33.0,
    acgihTlvTwa: 1,
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "A1 (Confirmed Human Carcinogen)",
    acgihTlvBasis: "Lung cancer; liver dam",
    acgihBei: null,
    nioshRelTwa: null,
    nioshRelStel: null,
    nioshRelC: null,
    nioshCa: true,
    oshaPelTwa: 1,
    oshaPelStel: 5,
    oshaPelC: null,
    idlh: "Ca [N.D.]",
    routes: "Inhalation, Contact",
    symptoms: "Weakness, abdominal pain, GI bleeding; enlarged liver; pallor or cyanosis of extremities; liver angiosarcoma; [carcinogen]",
    targetOrgans: "Liver, CNS, blood, respiratory system, lymphatic system",
    respirator: "ScbaF:Pd,Pp/SaF:Pd,Pp:AScba / Escape: GmFS/ScbaE",
    firstAid: "Eye: Frostbite wash; Skin: Frostbite treatment; Breath: Resp support"
  },
  {
    name: "Xylene (mixed isomers)",
    synonyms: "Dimethylbenzene, Xylol, mixed xylenes (m-, o-, p- isomers)",
    cas: "1330-20-7",
    rtecs: "ZE2100000",
    dot: "1307 130",
    formula: "C6H4(CH3)2",
    mw: 106.16,
    bp: "281°F (138.5°C)",
    vp20: 6.0,
    density: 0.865,
    flp: "81°F (27°C)",
    lel: 1.0,
    uel: 7.0,
    acgihTlvTwa: 20, // 2025 ACGIH Adopted Value: 20 ppm
    acgihTlvStel: null,
    acgihTlvC: null,
    acgihNotations: "OTO (Ototoxicant for p-xylene); A4; BEI",
    acgihTlvBasis: "Eye & URT irr; hematologic eff; ototoxicity; CNS impair",
    acgihBei: "Methylhippuric acids in urine: 0.3 g/g creatinine, End of shift",
    nioshRelTwa: 100,
    nioshRelStel: 150,
    nioshRelC: null,
    nioshCa: false,
    oshaPelTwa: 100,
    oshaPelStel: null,
    oshaPelC: null,
    idlh: "900 ppm",
    routes: "Inhalation, Skin absorption, Ingestion, Contact",
    symptoms: "Irritation of eyes, nose, throat; dizziness, excitement, drowsiness, incoordination, staggering gait; corneal vacuolization; anorexia, nausea, vomiting, abdominal pain; dermatitis",
    targetOrgans: "Eyes, skin, respiratory system, CNS, GI tract, blood, liver, kidneys",
    respirator: "900 ppm: CcrOv/PaprOv/GmFOv/Sa/ScbaF",
    firstAid: "Eye: Irrigate immediately; Skin: Soap wash prompt; Breath: Resp support; Swallow: Medical attention immediately"
  }
];

/**
 * ACGIH Physical Agents & Appendices Reference Data
 */
export const ACGIH_PHYSICAL_AGENTS = {
  // Audible Sound / Noise (Table 1 - 2025 ACGIH)
  noiseLimits: [
    { duration: "24 hours", soundPressureDba: 80 },
    { duration: "16 hours", soundPressureDba: 82 },
    { duration: "8 hours", soundPressureDba: 85 },
    { duration: "4 hours", soundPressureDba: 88 },
    { duration: "2 hours", soundPressureDba: 91 },
    { duration: "1 hour", soundPressureDba: 94 },
    { duration: "30 minutes", soundPressureDba: 97 },
    { duration: "15 minutes", soundPressureDba: 100 },
    { duration: "7.5 minutes", soundPressureDba: 103 },
    { duration: "3.75 minutes", soundPressureDba: 106 },
    { duration: "1.88 minutes", soundPressureDba: 109 },
    { duration: "0.94 minutes", soundPressureDba: 112 },
    { duration: "28.12 seconds", soundPressureDba: 115 },
    { duration: "14.06 seconds", soundPressureDba: 118 },
    { duration: "7.03 seconds", soundPressureDba: 121 },
    { duration: "3.52 seconds", soundPressureDba: 124 },
    { duration: "1.76 seconds", soundPressureDba: 127 },
    { duration: "0.88 seconds", soundPressureDba: 130 },
    { duration: "0.44 seconds", soundPressureDba: 133 },
    { duration: "0.22 seconds", soundPressureDba: 136 },
    { duration: "0.11 seconds", soundPressureDba: 139 },
    { duration: "0.08 seconds", soundPressureDba: 140 }
  ],

  // Heat Stress & Strain (WBGT Screening Criteria Table 3)
  heatStressScreening: [
    { workAllocation: "75% to 100% Work", lightWbgt: 31.0, moderateWbgt: 28.0, heavyWbgt: null, veryHeavyWbgt: null },
    { workAllocation: "50% to 75% Work", lightWbgt: 31.0, moderateWbgt: 29.0, heavyWbgt: 27.5, veryHeavyWbgt: null },
    { workAllocation: "25% to 50% Work", lightWbgt: 32.0, moderateWbgt: 30.0, heavyWbgt: 29.0, veryHeavyWbgt: 28.0 },
    { workAllocation: "0% to 25% Work", lightWbgt: 32.5, moderateWbgt: 31.5, heavyWbgt: 30.5, veryHeavyWbgt: 30.0 }
  ],

  // Hand-Arm Vibration (HAVS)
  handArmVibration: {
    tlv8hr: "5.0 m/s² (A(8))",
    actionLimit8hr: "2.5 m/s² (AL)",
    formulaTlv: "ahv(TLV) = 5.0 * (8 / Tv)^0.5",
    formulaAl: "ahv(AL) = 2.5 * (8 / Tv)^0.5"
  },

  // Hand Activity Level (HAL) Ergonomics
  handActivity: {
    formulaHal: "HAL = 6.56 * ln(D / (1 + 3.18 * F^1.31))",
    formulaTlv: "NPF_TLV = 0.56 * (10 - HAL)",
    formulaAl: "NPF_AL = NPF_TLV - 2.0"
  }
};
